-- RETORNA TODAS AS TUPLAS
SELECT * FROM PLATAFORMA;
SELECT * FROM JOGO;
SELECT * FROM EMPRESA;

-- RETORNA TODAS AS TUPLAS QUE ATENDEREM A CONDIÇÃO
SELECT * FROM PLATAFORMA
WHERE NOME = 'PlayStation 2';

-- RETORNA APENAS AS COLUNAS INDICADAS DAS TUPLAS QUE ATENDEREM A CONDIÇÃO
SELECT NOME, DATALANCAMENTO
FROM PLATAFORMA
WHERE NOME = 'PlayStation 2';

-- RETORNA, NA ORDEM INDICADA, APENAS AS COLUNAS INDICADAS DAS TUPLAS QUE ATENDEREM A CONDIÇÃO
SELECT NOME, DATALANCAMENTO
FROM PLATAFORMA
WHERE NOME = 'PlayStation 2'
ORDER BY DATALANCAMENTO;