SELECT 
    TABLE_NAME, 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE, 
    SEARCH_CONDITION, 
    R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'JOGO', 'TITULOALTERNATIVO', 'CONTEUDOADICIONAL', 
    'GENERO', 'CATEGORIZA', 
    'EMPRESA', 'DESENVOLVE', 'DISTRIBUI', 
    'PLATAFORMA', 'SUPORTA', 
    'AVALIADOR', 'AVALIACAO', 'AVALIA'
)
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;