SELECT TABLE_NAME, STATUS, NUM_ROWS
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'JOGO', 'TITULOALTERNATIVO', 'CONTEUDOADICIONAL', 
    'GENERO', 'CATEGORIZA', 
    'EMPRESA', 'DESENVOLVE', 'DISTRIBUI', 
    'PLATAFORMA', 'SUPORTA', 
    'AVALIADOR', 'AVALIACAO', 'AVALIA'
)
ORDER BY TABLE_NAME;