SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN (
    'JOGO', 'TITULOALTERNATIVO', 'CONTEUDOADICIONAL', 
    'GENERO', 'CATEGORIZA', 
    'EMPRESA', 'DESENVOLVE', 'DISTRIBUI', 
    'PLATAFORMA', 'SUPORTA', 
    'AVALIADOR', 'AVALIACAO', 'AVALIA'
)
ORDER BY TABLE_NAME, COLUMN_ID;