INSERT INTO AVALIACAO (
    AVALIADORID, AVALIACAOID, DATAPOST, NOTA, COMENTARIO
) VALUES (
    2,
    SEQ_AVALIACAO.NEXTVAL,
    SYSDATE,
    9.7,
    NULL
);

INSERT INTO AVALIA (
    JOGOID, PLATAFORMAID, AVALIADORID, AVALIACAOID
) VALUES (
    1, 1, 2, SEQ_AVALIACAO.CURRVAL
);


-- GOD OF WAR (2018)
INSERT INTO AVALIACAO (
    AVALIADORID, AVALIACAOID, DATAPOST, NOTA, COMENTARIO
) VALUES (
    3,
    SEQ_AVALIACAO.NEXTVAL,
    SYSDATE,
    9.4,
    NULL
);

INSERT INTO AVALIA VALUES (
    2, 2, 3, SEQ_AVALIACAO.CURRVAL
);


-- MINECRAFT — Avaliação por Mathenos2077 kkkk
INSERT INTO AVALIACAO (
    AVALIADORID, AVALIACAOID, DATAPOST, NOTA, COMENTARIO
) VALUES (
    1,
    SEQ_AVALIACAO.NEXTVAL,
    SYSDATE,
    9.0,
    NULL
);

INSERT INTO AVALIA VALUES (
    3, 4, 1, SEQ_AVALIACAO.CURRVAL  -- PC
);



-- MINECRAFT — Avaliação por IGN (outra plataforma)
INSERT INTO AVALIACAO (
    AVALIADORID, AVALIACAOID, DATAPOST, NOTA, COMENTARIO
) VALUES (
    2,
    SEQ_AVALIACAO.NEXTVAL,
    SYSDATE,
    8.8,
    NULL
);

INSERT INTO AVALIA VALUES (
    3, 3, 2, SEQ_AVALIACAO.CURRVAL  -- Xbox Series X
);

-- GTA V — Avaliado por IGN
INSERT INTO AVALIACAO (
    AVALIADORID, AVALIACAOID, DATAPOST, NOTA, COMENTARIO
) VALUES (
    2,
    SEQ_AVALIACAO.NEXTVAL,
    SYSDATE,
    9.6,
    NULL
);

INSERT INTO AVALIA VALUES (
    4, 4, 2, SEQ_AVALIACAO.CURRVAL
);

-- HOLLOW KNIGHT — Avaliado por Mathenos2077 '-'
INSERT INTO AVALIACAO (
    AVALIADORID, AVALIACAOID, DATAPOST, NOTA, COMENTARIO
) VALUES (
    1,
    SEQ_AVALIACAO.NEXTVAL,
    SYSDATE,
    9.2,
    NULL
);

INSERT INTO AVALIA VALUES (
    5, 4, 1, SEQ_AVALIACAO.CURRVAL
);

------------------------------------------------------------
-- FIM DO POPULATE
------------------------------------------------------------
COMMIT;
