-- INSERE UM "JOGO" NO BANCO DE DADOS

-- ITENS OBRIGATÓRIOS
DEFINE JOGO_TITULO = 'JOGO 1'
DEFINE JOGO_DATALANCAMENTO = '12/02/2001'
DEFINE EMPRESA_NOME = 'EMPRESA 1'
DEFINE PLATAFORMA_NOME = 'PLATAFORMA 1'

-- ITENS OPCIONAIS
DEFINE JOGO_SINOPSE = ''
DEFINE JOGO_CLASSIFICACAOINDICATIVA = ''

-- GENEROS E TITULOS ALTERNATIVOS, POR SEREM MULTIVALORADOS,
-- DEVEM SER ADICIONADOS ATRAVÉS DE SEUS RESPECTIVOS SCRIPTS

-- UTILS
VARIABLE JOGO_ID_CAPTURADO NUMBER


BEGIN

    -- INSERÇÃO DO JOGO

    INSERT INTO JOGO (
        TITULO,
        DATALANCAMENTO,
        SINOPSE,
        CLASSIFICACAOINDICATIVA
    )
    VALUES (
        '&JOGO_TITULO',
        TO_DATE('&JOGO_DATALANCAMENTO', 'DD/MM/YYYY'),
        '&JOGO_SINOPSE',
        '&JOGO_CLASSIFICACAOINDICATIVA'
    )
    RETURNING JOGOID INTO :JOGO_ID_CAPTURADO;

    -- TODO JOGO DEVE SER DESENVOLVIDO POR UMA EMPRESA

    INSERT INTO DESENVOLVE (
        EMPRESAID,
        JOGOID
    )
    VALUES (
        (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('&EMPRESA_NOME')),
        :JOGO_ID_CAPTURADO
    );

    -- TODO JOGO DEVE SER SUPORTADO POR UMA PLATAFORMA

    INSERT INTO SUPORTA (
        PLATAFORMAID,
        JOGOID
    )
    VALUES (
        (SELECT (PLATAFORMAID) FROM PLATAFORMA WHERE NOME IN ('&PLATAFORMA_NOME')),
        :JOGO_ID_CAPTURADO
    );

EXCEPTION

    WHEN OTHERS THEN
        ROLLBACK;

        RAISE_APPLICATION_ERROR(-20010, 'Erro ao criar jogo: ' || SQLERRM);

END;
/

COMMIT;