INSERT INTO PLATAFORMA (
    NOME,
    CATEGORIA,
    DATALANCAMENTO,
    FABRICANTE
)
VALUES(
    'PLATAFORMA 3',
    'CATEGORIA 3',
    TO_DATE('01/01/2000', 'DD/MM/YYYY'),
    'FABRICANTE 3'
);

COMMIT;