-- INSERTS DA TABELA PLATAFORMA

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE) 
VALUES (
    'Nintendo Switch',
    'Console',
    TO_DATE('03/03/2017', 'DD/MM/YYYY'),
    'Nintendo'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE) 
VALUES (
    'PlayStation 5',
    'Console',
    TO_DATE('12/11/2020', 'DD/MM/YYYY'),
    'Sony'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE)
VALUES (
    'Xbox Series X',
    'Console',
    TO_DATE('10/11/2020', 'DD/MM/YYYY'),
    'Microsoft'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE) 
VALUES (
    'PC',
    'PC',
    TO_DATE('01/01/1985', 'DD/MM/YYYY'),
    'Diversos'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE)
VALUES (
    'Android',
    'Mobile',
    TO_DATE('23/09/2008', 'DD/MM/YYYY'),
    'Google'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE) 
VALUES (
    'iOS',
    'Mobile',
    TO_DATE('29/06/2007', 'DD/MM/YYYY'),
    'Apple'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE) 
VALUES (
    'Nintendo 3DS',
    'Handheld',
    TO_DATE('26/02/2011', 'DD/MM/YYYY'),
    'Nintendo'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE) 
VALUES (
    'Steam Deck',
    'Handheld',
    TO_DATE('25/02/2022', 'DD/MM/YYYY'),
    'Valve'
);

INSERT INTO PLATAFORMA (NOME, CATEGORIA, DATALANCAMENTO, FABRICANTE) 
VALUES (
    'PlayStation 2',
    'Console',
    TO_DATE('04/03/2000', 'DD/MM/YYYY'),
    'Sony'
);


COMMIT;