-- INSERTS DA TABELA GENERO

INSERT INTO GENERO (NOME) VALUES ('Ação');
INSERT INTO GENERO (NOME) VALUES ('Aventura');
INSERT INTO GENERO (NOME) VALUES ('RPG');
INSERT INTO GENERO (NOME) VALUES ('RPG de Ação');
INSERT INTO GENERO (NOME) VALUES ('FPS');
INSERT INTO GENERO (NOME) VALUES ('TPS');
INSERT INTO GENERO (NOME) VALUES ('Corrida');
INSERT INTO GENERO (NOME) VALUES ('Esportes');
INSERT INTO GENERO (NOME) VALUES ('Luta');
INSERT INTO GENERO (NOME) VALUES ('Plataforma');
INSERT INTO GENERO (NOME) VALUES ('Simulação');
INSERT INTO GENERO (NOME) VALUES ('Estratégia');
INSERT INTO GENERO (NOME) VALUES ('RTS – Estratégia em Tempo Real');
INSERT INTO GENERO (NOME) VALUES ('Terror');
INSERT INTO GENERO (NOME) VALUES ('Puzzle');
INSERT INTO GENERO (NOME) VALUES ('Sandbox');
INSERT INTO GENERO (NOME) VALUES ('Survival');
INSERT INTO GENERO (NOME) VALUES ('MMO');
INSERT INTO GENERO (NOME) VALUES ('Cooperativo');
INSERT INTO GENERO (NOME) VALUES ('Multiplayer Competitivo');
INSERT INTO GENERO (NOME) VALUES ('Indie');
INSERT INTO GENERO (NOME) VALUES ('Metroidvania');
INSERT INTO GENERO (NOME) VALUES ('Souls-like');

COMMIT;