------------------------------------------------------------
-- INSERTS DA TABELA GENERO
-- Gera IDs usando SEQ_GENERO.NEXTVAL
------------------------------------------------------------

INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Ação');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Aventura');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'RPG');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'RPG de Ação');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'FPS');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'TPS');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Corrida');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Esportes');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Luta');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Plataforma');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Simulação');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Estratégia');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'RTS – Estratégia em Tempo Real');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Terror');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Puzzle');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Sandbox');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Survival');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'MMO');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Cooperativo');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Multiplayer Competitivo');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Indie');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Metroidvania');
INSERT INTO GENERO (GENEROID, NOME) VALUES (SEQ_GENERO.NEXTVAL, 'Souls-like');
