DECLARE
    ID_JOGO NUMBER;
BEGIN
    -- JOGO 1
    INSERT INTO JOGO (TITULO, DATALANCAMENTO, SINOPSE, CLASSIFICACAOINDICATIVA) 
    VALUES (
        'The Legend of Zelda: Breath of the Wild',
        TO_DATE('03/03/2017', 'DD/MM/YYYY'),
        'Um jogo de mundo aberto com exploração livre e alta interação com o ambiente.',
        '12'
    ) RETURNING JOGOID INTO ID_JOGO;
    INSERT INTO DESENVOLVE (JOGOID, EMPRESAID)
    VALUES (ID_JOGO, (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('Nintendo')));  
    INSERT INTO SUPORTA (JOGOID, PLATAFORMAID, PRECOLANCAMENTO, NUMVENDASGLOBAIS, NUMJOGADORESATIVOS)
    VALUES (ID_JOGO, (SELECT PLATAFORMAID FROM PLATAFORMA WHERE NOME IN ('Nintendo Switch')), NULL, 30000000, 1500000);
    INSERT INTO CATEGORIZA (JOGOID, GENEROID) 
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('Ação')));
    INSERT INTO CATEGORIZA (JOGOID, GENEROID) 
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('RPG')));
    INSERT INTO CONTEUDOADICIONAL (JOGOID, TITULO, DATALANCAMENTO, CATEGORIA) 
    VALUES (ID_JOGO, 'The Master Trials', TO_DATE('30/06/2017', 'DD/MM/YYYY'), 'DLC');
    INSERT INTO CONTEUDOADICIONAL (JOGOID, TITULO, DATALANCAMENTO, CATEGORIA) 
    VALUES (ID_JOGO, 'The Champions Ballad', TO_DATE('07/12/2017', 'DD/MM/YYYY'), 'DLC');

    -- JOGO 2
    INSERT INTO JOGO (TITULO, DATALANCAMENTO, SINOPSE, CLASSIFICACAOINDICATIVA) 
    VALUES (
        'God of War (2018)',
        TO_DATE('20/04/2018', 'DD/MM/YYYY'),
        'Kratos embarca em uma jornada com seu filho pelos reinos nórdicos.',
        '18'
    ) RETURNING JOGOID INTO ID_JOGO;
    INSERT INTO DESENVOLVE (JOGOID, EMPRESAID)
    VALUES (ID_JOGO, (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('Sony Interactive Entertainment')));  
    INSERT INTO DISTRIBUI (JOGOID, EMPRESAID)
    VALUES (ID_JOGO, (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('Sony Interactive Entertainment'))); 
    INSERT INTO SUPORTA (JOGOID, PLATAFORMAID, PRECOLANCAMENTO, NUMVENDASGLOBAIS, NUMJOGADORESATIVOS)
    VALUES (ID_JOGO, (SELECT PLATAFORMAID FROM PLATAFORMA WHERE NOME IN ('PlayStation 5')), NULL, 19000000, 900000);
    INSERT INTO CATEGORIZA (JOGOID, GENEROID) 
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('RPG de Ação')));

    -- JOGO 3
    INSERT INTO JOGO (TITULO, DATALANCAMENTO, SINOPSE, CLASSIFICACAOINDICATIVA) 
    VALUES (
        'Minecraft',
        TO_DATE('18/11/2011', 'DD/MM/YYYY'),
        'Jogo sandbox focado em construção, criatividade e sobrevivência.',
        'Livre'
    ) RETURNING JOGOID INTO ID_JOGO;
    INSERT INTO DESENVOLVE (JOGOID, EMPRESAID)
    VALUES (ID_JOGO, (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('Ubisoft')));  
    INSERT INTO DESENVOLVE (JOGOID, EMPRESAID)
    VALUES (ID_JOGO, (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('SEGA'))); 
    INSERT INTO SUPORTA (JOGOID, PLATAFORMAID, PRECOLANCAMENTO, NUMVENDASGLOBAIS, NUMJOGADORESATIVOS)
    VALUES (ID_JOGO, (SELECT PLATAFORMAID FROM PLATAFORMA WHERE NOME IN ('Xbox Series X')), NULL, 19000000, 900000);
    INSERT INTO SUPORTA (JOGOID, PLATAFORMAID, PRECOLANCAMENTO, NUMVENDASGLOBAIS, NUMJOGADORESATIVOS)
    VALUES (ID_JOGO, (SELECT PLATAFORMAID FROM PLATAFORMA WHERE NOME IN ('PC')), NULL, 238000000, 10000000);
    INSERT INTO CATEGORIZA (JOGOID, GENEROID) 
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('Sandbox')));

    

    -- JOGO 4
    INSERT INTO JOGO (TITULO, DATALANCAMENTO, SINOPSE, CLASSIFICACAOINDICATIVA) 
    VALUES (
        'GTA V',
        TO_DATE('17/09/2013', 'DD/MM/YYYY'),
        'Um dos jogos mais vendidos da história, com mundo aberto extenso.',
        '18'
    ) RETURNING JOGOID INTO ID_JOGO;
    INSERT INTO DESENVOLVE (JOGOID, EMPRESAID)
    VALUES (ID_JOGO, (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('Rockstar Games')));  
    INSERT INTO SUPORTA (JOGOID, PLATAFORMAID, PRECOLANCAMENTO, NUMVENDASGLOBAIS, NUMJOGADORESATIVOS)
    VALUES (ID_JOGO, (SELECT PLATAFORMAID FROM PLATAFORMA WHERE NOME IN ('PC')), NULL, 200000000, 6000000);
    INSERT INTO CATEGORIZA (JOGOID, GENEROID) 
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('Ação')));
    INSERT INTO CATEGORIZA (JOGOID, GENEROID) 
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('Corrida')));

    -- JOGO 5
    INSERT INTO JOGO (TITULO, DATALANCAMENTO, SINOPSE, CLASSIFICACAOINDICATIVA) 
    VALUES (
        'Hollow Knight',
        TO_DATE('24/02/2017', 'DD/MM/YYYY'),
        'Um metroidvania desafiador com foco em exploração e atmosfera.',
        '10'
    ) RETURNING JOGOID INTO ID_JOGO;
    INSERT INTO DESENVOLVE (JOGOID, EMPRESAID)
    VALUES (ID_JOGO, (SELECT EMPRESAID FROM EMPRESA WHERE NOME IN ('SEGA')));  
    INSERT INTO SUPORTA (JOGOID, PLATAFORMAID, PRECOLANCAMENTO, NUMVENDASGLOBAIS, NUMJOGADORESATIVOS)
    VALUES (ID_JOGO, (SELECT PLATAFORMAID FROM PLATAFORMA WHERE NOME IN ('PC')), NULL, 6000000, 500000);
    INSERT INTO CATEGORIZA  (JOGOID, GENEROID)
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('Ação')));
    INSERT INTO CATEGORIZA  (JOGOID, GENEROID)
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('Aventura')));
    INSERT INTO CATEGORIZA  (JOGOID, GENEROID)
    VALUES (ID_JOGO, (SELECT GENEROID FROM GENERO WHERE NOME IN ('Plataforma')));
    INSERT INTO CONTEUDOADICIONAL (JOGOID, TITULO, DATALANCAMENTO, CATEGORIA) 
    VALUES (ID_JOGO, 'Hidden Dreams', TO_DATE('07/06/2017', 'DD/MM/YYYY'), 'DLC');
    INSERT INTO CONTEUDOADICIONAL (JOGOID, TITULO, DATALANCAMENTO, CATEGORIA) 
    VALUES (ID_JOGO, 'The Grimm Troupe', TO_DATE('14/09/2017', 'DD/MM/YYYY'), 'DLC');
    INSERT INTO CONTEUDOADICIONAL (JOGOID, TITULO, DATALANCAMENTO, CATEGORIA) 
    VALUES (ID_JOGO, 'Lifeblood', TO_DATE('23/03/2017', 'DD/MM/YYYY'), 'DLC');
    INSERT INTO CONTEUDOADICIONAL (JOGOID, TITULO, DATALANCAMENTO, CATEGORIA) 
    VALUES (ID_JOGO, 'Godmaster', TO_DATE('30/01/2018', 'DD/MM/YYYY'), 'DLC');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20010, 'Erro ao registrar jogo: ' || SQLERRM);
END;
/

COMMIT;