DROP TABLE AVALIA CASCADE CONSTRAINTS;
DROP TABLE CATEGORIZA CASCADE CONSTRAINTS;
DROP TABLE DESENVOLVE CASCADE CONSTRAINTS;
DROP TABLE DISTRIBUI CASCADE CONSTRAINTS;
DROP TABLE SUPORTA CASCADE CONSTRAINTS;

DROP TABLE TITULOALTERNATIVO CASCADE CONSTRAINTS;
DROP TABLE CONTEUDOADICIONAL CASCADE CONSTRAINTS;
DROP TABLE AVALIACAO CASCADE CONSTRAINTS;

DROP TABLE JOGO CASCADE CONSTRAINTS;
DROP TABLE GENERO CASCADE CONSTRAINTS;
DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE PLATAFORMA CASCADE CONSTRAINTS;
DROP TABLE AVALIADOR CASCADE CONSTRAINTS;