------------------------------------------------------------
-- SEQUENCES
------------------------------------------------------------
CREATE SEQUENCE SEQ_JOGO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GENERO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPRESA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLATAFORMA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AVALIADOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTEUDO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AVALIACAO START WITH 1 INCREMENT BY 1;

------------------------------------------------------------
-- TABELA JOGO
------------------------------------------------------------
CREATE TABLE JOGO(
    JOGOID NUMBER PRIMARY KEY,
    TITULO VARCHAR2(255) NOT NULL,
    DATALANCAMENTO DATE NOT NULL,
    SINOPSE VARCHAR2(4000),
    CLASSIFICACAOINDICATIVA VARCHAR2(50)
);

------------------------------------------------------------
-- TABELA TITULOALTERNATIVO
------------------------------------------------------------
CREATE TABLE TITULOALTERNATIVO (
    JOGOID NUMBER NOT NULL,
    TITULO VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_TITULOALTER PRIMARY KEY (JOGOID, TITULO),
    CONSTRAINT FK_TITULOALTER_JOGO FOREIGN KEY (JOGOID)
        REFERENCES JOGO(JOGOID)
);

------------------------------------------------------------
-- TABELA CONTEUDOADICIONAL
------------------------------------------------------------
CREATE TABLE CONTEUDOADICIONAL (
    CONTEUDOADICIONALID NUMBER PRIMARY KEY,
    JOGOID NUMBER NOT NULL,
    TITULO VARCHAR2(255) NOT NULL,
    DATALANCAMENTO DATE NOT NULL,
    CATEGORIA VARCHAR2(100) NOT NULL,

    CONSTRAINT FK_CONTADD_JOGO FOREIGN KEY (JOGOID)
        REFERENCES JOGO(JOGOID)
);

------------------------------------------------------------
-- TABELA GENERO
------------------------------------------------------------
CREATE TABLE GENERO (
    GENEROID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) UNIQUE NOT NULL
);

------------------------------------------------------------
-- TABELA CATEGORIZA
------------------------------------------------------------
CREATE TABLE CATEGORIZA (
    JOGOID NUMBER NOT NULL,
    GENEROID NUMBER NOT NULL,

    CONSTRAINT PK_CATEGORIZA PRIMARY KEY (JOGOID, GENEROID),
    CONSTRAINT FK_CATEGORIZA_JOGO FOREIGN KEY (JOGOID)
        REFERENCES JOGO(JOGOID),
    CONSTRAINT FK_CATEGORIZA_GENERO FOREIGN KEY (GENEROID)
        REFERENCES GENERO(GENEROID)
);

------------------------------------------------------------
-- TABELA EMPRESA
------------------------------------------------------------
CREATE TABLE EMPRESA (
    EMPRESAID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) UNIQUE NOT NULL,
    PAISSEDE VARCHAR2(100),
    DATAFUNDACAO DATE,
    SITE VARCHAR2(255),
    ESTADO VARCHAR2(50),
    DESCRICAO VARCHAR2(800)
);

------------------------------------------------------------
-- TABELA DESENVOLVE
------------------------------------------------------------
CREATE TABLE DESENVOLVE (
    EMPRESAID NUMBER NOT NULL,
    JOGOID NUMBER NOT NULL,

    CONSTRAINT PK_DESENVOLVE PRIMARY KEY (EMPRESAID, JOGOID),
    CONSTRAINT FK_DESENVOLVE_EMP FOREIGN KEY (EMPRESAID)
        REFERENCES EMPRESA(EMPRESAID),
    CONSTRAINT FK_DESENVOLVE_JOGO FOREIGN KEY (JOGOID)
        REFERENCES JOGO(JOGOID)
);

------------------------------------------------------------
-- TABELA DISTRIBUI
------------------------------------------------------------
CREATE TABLE DISTRIBUI (
    EMPRESAID NUMBER NOT NULL,
    JOGOID NUMBER NOT NULL,

    CONSTRAINT PK_DISTRIBUI PRIMARY KEY (EMPRESAID, JOGOID),
    CONSTRAINT FK_DISTRIBUI_EMP FOREIGN KEY (EMPRESAID)
        REFERENCES EMPRESA(EMPRESAID),
    CONSTRAINT FK_DISTRIBUI_JOGO FOREIGN KEY (JOGOID)
        REFERENCES JOGO(JOGOID)
);

------------------------------------------------------------
-- TABELA PLATAFORMA
------------------------------------------------------------
CREATE TABLE PLATAFORMA (
    PLATAFORMAID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) UNIQUE NOT NULL,
    CATEGORIA VARCHAR2(100) NOT NULL,
    DATALANCAMENTO DATE NOT NULL,
    FABRICANTE VARCHAR2(100) NOT NULL
);

------------------------------------------------------------
-- TABELA SUPORTA
------------------------------------------------------------
CREATE TABLE SUPORTA (
    PLATAFORMAID NUMBER NOT NULL,
    JOGOID NUMBER NOT NULL,
    PRECOLANCAMENTO NUMBER,
    NUMVENDASGLOBAIS NUMBER,
    NUMJOGADORESATIVOS NUMBER,

    CONSTRAINT PK_SUPORTA PRIMARY KEY (PLATAFORMAID, JOGOID),
    CONSTRAINT FK_SUPORTA_PLAT FOREIGN KEY (PLATAFORMAID)
        REFERENCES PLATAFORMA(PLATAFORMAID),
    CONSTRAINT FK_SUPORTA_JOGO FOREIGN KEY (JOGOID)
        REFERENCES JOGO(JOGOID)
);

------------------------------------------------------------
-- TABELA AVALIADOR
------------------------------------------------------------
CREATE TABLE AVALIADOR (
    AVALIADORID NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    TIPO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255),
    URL VARCHAR2(255),
    PAISORIGEM VARCHAR2(100),
    DESCRICAO VARCHAR2(4000)
);

------------------------------------------------------------
-- TABELA AVALIACAO
------------------------------------------------------------
CREATE TABLE AVALIACAO (
    AVALIACAOID NUMBER PRIMARY KEY,
    AVALIADORID NUMBER NOT NULL,
    DATAPOST DATE NOT NULL,
    NOTA NUMBER(3,1) NOT NULL,
    COMENTARIO VARCHAR2(4000),

    CONSTRAINT FK_AVALIACAO_AVALIADOR FOREIGN KEY (AVALIADORID)
        REFERENCES AVALIADOR(AVALIADORID)
);

------------------------------------------------------------
-- TABELA AVALIA
------------------------------------------------------------
CREATE TABLE AVALIA (
    JOGOID NUMBER NOT NULL,
    PLATAFORMAID NUMBER NOT NULL,
    AVALIADORID NUMBER NOT NULL,
    AVALIACAOID NUMBER NOT NULL,

    CONSTRAINT PK_AVALIA PRIMARY KEY (JOGOID, PLATAFORMAID, AVALIADORID, AVALIACAOID),

    CONSTRAINT FK_AVALIA_JOGO FOREIGN KEY (JOGOID)
        REFERENCES JOGO(JOGOID),
    CONSTRAINT FK_AVALIA_PLAT FOREIGN KEY (PLATAFORMAID)
        REFERENCES PLATAFORMA(PLATAFORMAID),
    CONSTRAINT FK_AVALIA_AVALIACAO FOREIGN KEY (AVALIADORID)
        REFERENCES AVALIADOR(AVALIADORID),
    CONSTRAINT FK_AVALIA_AVALIACAO2 FOREIGN KEY (AVALIACAOID)
        REFERENCES AVALIACAO(AVALIACAOID)
);
