-- JOGO - ENTIDADE
CREATE TABLE JOGO(
    JOGOID NUMBER(20) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_JOGO PRIMARY KEY,
    TITULO VARCHAR2(255) NOT NULL,
    DATALANCAMENTO DATE NOT NULL,
    SINOPSE VARCHAR2(4000) NULL,
    CLASSIFICACAOINDICATIVA VARCHAR2(50) NULL
);

-- TÍTULO ALTERNATIVO - ATRIBUTO MULTIVALORADO DE JOGO
CREATE TABLE TITULOALTERNATIVO (
    JOGOID NUMBER(20) NOT NULL,
    TITULO VARCHAR2(255) NOT NULL,

    CONSTRAINT PK_TITULOALTERNATIVO PRIMARY KEY (JOGOID, TITULO),

    CONSTRAINT FK_JOGO_TITULOALTERNATIVO FOREIGN KEY (JOGOID) 
    REFERENCES JOGO(JOGOID) ON DELETE CASCADE
);

-- CONTEÚDO ADICIONAL - ENTIDADE FRACA DE JOGO
CREATE TABLE CONTEUDOADICIONAL (
    JOGOID NUMBER(20) NOT NULL,
    CONTEUDOADICIONALID NUMBER(20) GENERATED ALWAYS AS IDENTITY,
    TITULO VARCHAR2(255) NOT NULL,
    DATALANCAMENTO DATE NOT NULL,
    CATEGORIA VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_CONTEUDOADICIONAL PRIMARY KEY (JOGOID, CONTEUDOADICIONALID),

    CONSTRAINT FK_JOGO_CONTEUDOADICIONAL FOREIGN KEY (JOGOID) 
    REFERENCES JOGO(JOGOID) ON DELETE CASCADE
);

-- GENERO - ENTIDADE
CREATE TABLE GENERO (
    GENEROID NUMBER(20)  GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(255) UNIQUE NOT NULL,

    CONSTRAINT PK_GENERO PRIMARY KEY (GENEROID)
);

-- CATEGORIZA - RELACIONA JOGOS À GÊNEROS
CREATE TABLE CATEGORIZA (
    JOGOID NUMBER(20) NOT NULL,
    GENEROID NUMBER(20) NOT NULL,

    CONSTRAINT PK_CATEGORIZA PRIMARY KEY (JOGOID, GENEROID),

    CONSTRAINT FK_GENERO_CATEGORIZA FOREIGN KEY (GENEROID)
    REFERENCES GENERO(GENEROID) ON DELETE CASCADE,

    CONSTRAINT FK_JOGO_CATEGORIZA FOREIGN KEY (JOGOID)
    REFERENCES JOGO(JOGOID) ON DELETE CASCADE
);

-- EMPRESA - ENTIDADE
CREATE TABLE EMPRESA (
    EMPRESAID NUMBER(20)  GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(255) UNIQUE NOT NULL,
    PAISSEDE VARCHAR2(100) NULL,
    DATAFUNDACAO DATE NULL,
    SITE VARCHAR2(255) NULL,
    ESTADO VARCHAR2(50) NULL,
    DESCRICAO VARCHAR2(800) NULL,

    CONSTRAINT PK_EMPRESA PRIMARY KEY (EMPRESAID)
);

-- DESENVOLVE - RELACIONA EMPRESAS QUE DESENVOLVERAM JOGOS
CREATE TABLE DESENVOLVE (
    EMPRESAID NUMBER(20) NOT NULL,
    JOGOID NUMBER(20) NOT NULL,

    CONSTRAINT PK_DESENVOLVE PRIMARY KEY (EMPRESAID, JOGOID),

    CONSTRAINT FK_EMPRESA_DESENVOLVE FOREIGN KEY (EMPRESAID)
    REFERENCES EMPRESA(EMPRESAID) ON DELETE CASCADE,

    CONSTRAINT FK_JOGO_DESENVOLVE FOREIGN KEY (JOGOID)
    REFERENCES JOGO(JOGOID) ON DELETE CASCADE
);

-- DISTRIBUI - RELACIONA EMPRESAS QUE DISTRIBUÍRAM JOGOS
CREATE TABLE DISTRIBUI (
    EMPRESAID NUMBER(20) NOT NULL,
    JOGOID NUMBER(20) NOT NULL,

    CONSTRAINT PK_DISTRIBUI PRIMARY KEY (EMPRESAID, JOGOID),

    CONSTRAINT FK_EMPRESA_DISTRIBUI FOREIGN KEY (EMPRESAID)
    REFERENCES EMPRESA(EMPRESAID) ON DELETE CASCADE,

    CONSTRAINT FK_JOGO_DISTRIBUI FOREIGN KEY (JOGOID)
    REFERENCES JOGO(JOGOID) ON DELETE CASCADE
);

-- PLATAFORMA - ENTIDADE
CREATE TABLE PLATAFORMA (
    PLATAFORMAID NUMBER(20)  GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(255) UNIQUE NOT NULL,
    CATEGORIA VARCHAR2(100) NOT NULL,
    DATALANCAMENTO DATE NOT NULL,
    FABRICANTE VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_PLATAFORMA PRIMARY KEY (PLATAFORMAID)
);

-- SUPORTA - RELACIONA PLATAFORMAS E JOGOS
CREATE TABLE SUPORTA (
    PLATAFORMAID NUMBER(20) NOT NULL,
    JOGOID NUMBER(20) NOT NULL,
    PRECOLANCAMENTO NUMBER(10,2) NULL,
    NUMVENDASGLOBAIS NUMBER(10) NULL,
    NUMJOGADORESATIVOS NUMBER(10) NULL,

    CONSTRAINT PK_SUPORTA PRIMARY KEY (PLATAFORMAID, JOGOID),

    CONSTRAINT FK_PLATAFORMA_SUPORTA FOREIGN KEY (PLATAFORMAID)
    REFERENCES PLATAFORMA(PLATAFORMAID) ON DELETE CASCADE,

    CONSTRAINT FK_JOGO_SUPORTA FOREIGN KEY (JOGOID)
    REFERENCES JOGO(JOGOID) ON DELETE CASCADE
);

-- AVALIADOR - ENTIDADE
CREATE TABLE AVALIADOR (
    AVALIADORID NUMBER(20)  GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR2(255) NOT NULL,
    TIPO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NULL,
    URL VARCHAR2(255) NULL,
    PAISORIGEM VARCHAR2(100) NULL,
    DESCRICAO VARCHAR2(4000) NULL,

    CONSTRAINT PK_AVALIADOR PRIMARY KEY (AVALIADORID)
);

-- AVALIACAO - ENTIDADE FRACA DE AVALIADOR
CREATE TABLE AVALIACAO (
    AVALIADORID NUMBER(20) NOT NULL,
    AVALIACAOID NUMBER(20)  GENERATED ALWAYS AS IDENTITY,
    DATAPOST DATE NOT NULL,
    NOTA NUMBER(3,1) NOT NULL,
    COMENTARIO VARCHAR2(4000) NULL,

    CONSTRAINT PK_AVALIACAO PRIMARY KEY (AVALIADORID, AVALIACAOID),

    CONSTRAINT FK_AVALIADOR_AVALIACAO FOREIGN KEY (AVALIADORID)
    REFERENCES AVALIADOR(AVALIADORID) ON DELETE CASCADE
);

-- RELACIONA AVALIAÇÕES COM UM JOGO E UMA PLATAFORMA
CREATE TABLE AVALIA (
    JOGOID NUMBER(20) NOT NULL,
    PLATAFORMAID NUMBER(20) NOT NULL,
    AVALIADORID NUMBER(20) NOT NULL,
    AVALIACAOID NUMBER(20) NOT NULL,

    CONSTRAINT PK_AVALIA PRIMARY KEY (JOGOID, PLATAFORMAID, AVALIADORID, AVALIACAOID),

    CONSTRAINT FK_JOGO_AVALIA FOREIGN KEY (JOGOID)
    REFERENCES JOGO(JOGOID) ON DELETE CASCADE,

    CONSTRAINT FK_PLATAFORMA_AVALIA FOREIGN KEY (PLATAFORMAID)
    REFERENCES PLATAFORMA(PLATAFORMAID) ON DELETE CASCADE,

    CONSTRAINT FK_AVALIACAO_AVALIA FOREIGN KEY (AVALIADORID, AVALIACAOID)
    REFERENCES AVALIACAO(AVALIADORID, AVALIACAOID) ON DELETE CASCADE
);